import { Game, Product } from "@/types";

export const mockGames: Game[] = [
  {
    id: "tul-1",
    name: "Mahj918 – Open Play @ McNellie's South City",
    organizerName: "Candace & Nicolle",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "McNellie's South City",
    address: "Tulsa, OK (South City location — confirm exact address in bio)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "monday",
      startTime: "18:00",
      endTime: "20:30",
      frequency: "monthly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0.0,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://mahj918.com",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description: "Regular American Mahjong open play nights hosted by Mahj918. Fun, social, all skill levels welcome. Held at McNellie's South City on select Mondays. Part of the monthly Mahj918 events calendar.",
    howToJoin: "Drop in or DM @mahj.918 on Instagram. Calendar link in bio.",
    whatToBring: "NMJL card; tiles if you have them",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: false,
    maxPlayers: null,
    typicalGroupSize: "12-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-2",
    name: "Mahj918 – Open Play @ McNellie's South City (Mar 2)",
    organizerName: "Candace & Nicolle",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "McNellie's South City",
    address: "Tulsa, OK (South City location — confirm in bio)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-02",
    eventStartTime: "18:00",
    eventEndTime: "20:30",
    cost: "Free",
    costAmount: 0.0,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://mahj918.com",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description: "Mahj918 open play night at McNellie's South City. Fun, social American Mahjong for all levels.",
    howToJoin: "Drop in or DM @mahj.918. Calendar link in Instagram bio.",
    whatToBring: "NMJL card; tiles if you have them",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: false,
    maxPlayers: null,
    typicalGroupSize: "12-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-3",
    name: "Mahj918 – Birdy's March Madness: Open Play & Birdy Basics (Mar 5)",
    organizerName: "Candace & Nicolle",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Broken Arrow / Tulsa Metro",
    venueName: "Bello Boardroom – Broken Arrow",
    address: "Broken Arrow, OK (exact address in Instagram bio)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-05",
    eventStartTime: "18:30",
    eventEndTime: "21:00",
    cost: "Varies",
    costAmount: null,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://mahj918.com",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description: "Special themed event — Birdy's March Madness! Combines a Birdy Basics beginner lesson with open play at Bello Boardroom in Broken Arrow. Great intro event for new players.",
    howToJoin: "RSVP preferred — DM @mahj.918 or email mahj918@yahoo.com.",
    whatToBring: "NMJL card if you have one; everything else provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "12-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-4",
    name: "Mahj918 – Birdy Basics Beginner Lesson @ JFT (Mar 8)",
    organizerName: "Candace & Nicolle",
    type: "lesson",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "Jewish Federation of Tulsa / CSJCC",
    address: "2021 E 71st St, Tulsa, OK 74136",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-08",
    eventStartTime: "12:30",
    eventEndTime: "16:30",
    cost: "$72",
    costAmount: 72.0,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://jewishtulsa.org/event/mahj918",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "https://jewishtulsa.org/event/mahj918",
    description: "Deep-dive 4-hour beginner Birdy Basics lesson taught by Mahj918 at the Jewish Federation of Tulsa. Includes 2025 NMJL card, booklet, snacks, and a refreshment break. After the session, attendees are invited to play with intermediate players. Must register by March 5.",
    howToJoin: "Register by March 5 at jewishtulsa.org/event/mahj918.",
    whatToBring: "Nothing — all materials, card, and snacks included in $72 fee",
    skillLevels: ["beginner"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "16-24",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-5",
    name: "Mahj918 – Private Birdy Basics (Mar 10)",
    organizerName: "Candace & Nicolle",
    type: "lesson",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Tulsa",
    venueName: "Private (location TBA)",
    address: "Tulsa, OK",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-10",
    eventStartTime: "",
    eventEndTime: "",
    cost: "Varies",
    costAmount: null,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://mahj918.com",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description: "Private Birdy Basics beginner lesson hosted by Mahj918. Details not publicly listed — contact for info.",
    howToJoin: "Contact mahj918@yahoo.com or DM @mahj.918 for private bookings.",
    whatToBring: "Nothing; all provided",
    skillLevels: ["beginner"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-6",
    name: "Mahj918 – Open Play & Birdy Basics @ Cyntergy Downtown (Mar 12)",
    organizerName: "Candace & Nicolle",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Downtown Tulsa",
    venueName: "Cyntergy – Downtown Tulsa",
    address: "Downtown Tulsa, OK (confirm exact address in Instagram bio)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-12",
    eventStartTime: "18:00",
    eventEndTime: "20:30",
    cost: "Varies",
    costAmount: null,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://mahj918.com",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description: "Combined Birdy Basics beginner lesson + open play at Cyntergy in Downtown Tulsa. Great for newcomers and experienced players alike.",
    howToJoin: "DM @mahj.918 or email mahj918@yahoo.com for details.",
    whatToBring: "NMJL card if you have one",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "16-24",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-7",
    name: "Mahj918 – Private Birdy Basics (Mar 13 & 15)",
    organizerName: "Candace & Nicolle",
    type: "lesson",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Tulsa",
    venueName: "Private (location TBA)",
    address: "Tulsa, OK",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-13",
    eventStartTime: "",
    eventEndTime: "",
    cost: "Varies",
    costAmount: null,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://mahj918.com",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description: "Private Birdy Basics beginner lessons on Friday Mar 13 and Sunday Mar 15. Contact Mahj918 for private event bookings.",
    howToJoin: "Contact mahj918@yahoo.com or DM @mahj.918.",
    whatToBring: "Nothing; all provided",
    skillLevels: ["beginner"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-8",
    name: "Mahj918 – Shamrock & Mahj Open Play @ McNellie's South City (Mar 16)",
    organizerName: "Candace & Nicolle",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "McNellie's South City",
    address: "Tulsa, OK (South City location — confirm in bio)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-16",
    eventStartTime: "18:00",
    eventEndTime: "20:30",
    cost: "Free",
    costAmount: 0.0,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://mahj918.com",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description: "St. Patrick's Day themed open play night — Shamrock & Mahj! American Mahjong open play at McNellie's South City. Fun, festive, all levels welcome.",
    howToJoin: "Drop in or DM @mahj.918. Calendar link in bio.",
    whatToBring: "NMJL card; tiles if you have them; green encouraged!",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: false,
    maxPlayers: null,
    typicalGroupSize: "12-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-9",
    name: "Mahj918 – 1st Annual Tournament (Mar 22)",
    organizerName: "Candace & Nicolle",
    type: "event",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Tulsa",
    venueName: "TBA (likely Cyntergy or similar)",
    address: "Tulsa, OK (TBA — check Instagram for venue announcement)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-22",
    eventStartTime: "13:00",
    eventEndTime: "18:00",
    cost: "TBA (est. $25–50)",
    costAmount: null,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://mahj918.com",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description: "Mahj918's first-ever American Mahjong tournament! Multiple skill levels (Sparrow and Crane divisions). Check-in at 11:30 AM, play starts 1 PM. Prizes for winners.",
    howToJoin: "Register via Instagram DM or email. Watch @mahj.918 for registration link.",
    whatToBring: "2026 NMJL card",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "40-64",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-10",
    name: "Mahj918 – Open Play & Birdy Basics @ Cyntergy Downtown (Mar 26)",
    organizerName: "Candace & Nicolle",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Downtown Tulsa",
    venueName: "Cyntergy – Downtown Tulsa",
    address: "Downtown Tulsa, OK (confirm exact address in Instagram bio)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-26",
    eventStartTime: "18:00",
    eventEndTime: "20:30",
    cost: "Varies",
    costAmount: null,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://mahj918.com",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description: "Combined Birdy Basics beginner lesson + open play at Cyntergy in Downtown Tulsa. All levels welcome.",
    howToJoin: "DM @mahj.918 or email mahj918@yahoo.com.",
    whatToBring: "NMJL card if you have one",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "16-24",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-11",
    name: "Mahj918 – Open Play @ McNellie's South City (Mar 30)",
    organizerName: "Candace & Nicolle",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "McNellie's South City",
    address: "Tulsa, OK (South City location — confirm in bio)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-30",
    eventStartTime: "18:00",
    eventEndTime: "20:30",
    cost: "Free",
    costAmount: 0.0,
    contactName: "Candace & Nicolle",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://mahj918.com",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description: "Mahj918 open play night at McNellie's South City. Fun, social American Mahjong for all levels.",
    howToJoin: "Drop in or DM @mahj.918. Calendar link in Instagram bio.",
    whatToBring: "NMJL card; tiles if you have them",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: false,
    maxPlayers: null,
    typicalGroupSize: "12-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-12",
    name: "CSJCC Sunday Mahjong Meetup (Recurring)",
    organizerName: "Laura Allen / Sarah Howman",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "Charles Schusterman Jewish Community Center",
    address: "2021 E 71st St, Tulsa, OK 74136",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "sunday",
      startTime: "14:00",
      endTime: "17:00",
      frequency: "weekly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0.0,
    contactName: "Laura Allen / Sarah Howman",
    contactEmail: "lallen@jewishtulsa.org",
    contactPhone: "",
    website: "https://jewishtulsa.org/event/mahjong-meetup/",
    instagram: "",
    facebookGroup: "",
    registrationLink: "https://www.meetup.com/csjcc-mahjong-meetup-group",
    description: "Weekly Sunday American Mahjong open play at the CSJCC. Beginner-friendly tables and intermediate/advanced tables both available. Members and non-members welcome. RSVP via Meetup preferred.",
    howToJoin: "RSVP weekly on Meetup (group: csjcc-mahjong-meetup-group) or check jewishtulsa.org.",
    whatToBring: "NMJL card; tiles if preferred (not required)",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: false,
    maxPlayers: null,
    typicalGroupSize: "20-40",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-13",
    name: "Mahjongg Tulsa – Open Play @ Barnes & Noble Southroads",
    organizerName: "Pat (organizer)",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "Barnes & Noble Southroads",
    address: "5231 E 41st St, Tulsa, OK 74135",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "monday|wednesday|friday",
      startTime: "12:00",
      endTime: "15:00",
      frequency: "weekly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$4",
    costAmount: 4.0,
    contactName: "Pat (organizer)",
    contactEmail: "",
    contactPhone: "",
    website: "https://www.meetup.com/meetup-group-jkbimwpu",
    instagram: "",
    facebookGroup: "",
    registrationLink: "https://www.meetup.com/meetup-group-jkbimwpu",
    description: "Long-running Meetup group for experienced American Mahjong players at Barnes & Noble Southroads. Fast-paced play (~15 min/game). No teaching during sessions. NMJL card required. $4 fee + please purchase a drink/snack to support the venue.",
    howToJoin: "RSVP on Meetup.com (Mahjongg Tulsa). Experienced players only — must know how to play.",
    whatToBring: "NMJL card; own tiles preferred",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: false,
    maxPlayers: null,
    typicalGroupSize: "12-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-14",
    name: "Oklahoma Riichi Open – Annual Tournament (Mar 14–15, 2026)",
    organizerName: "Ashlee Leak (Treasurer); Zac Leak",
    type: "event",
    gameStyle: "riichi",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "Embassy Suites Tulsa",
    address: "3332 S 79th E Ave, Tulsa, OK 74145",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-14",
    eventStartTime: "09:30",
    eventEndTime: "18:00",
    cost: "$50–$60",
    costAmount: 55.0,
    contactName: "Ashlee Leak (Treasurer); Zac Leak",
    contactEmail: "ashleefeather@yahoo.com",
    contactPhone: "",
    website: "https://oklahomamahjong.com/tournament/",
    instagram: "@ok.mahjong",
    facebookGroup: "https://www.facebook.com/groups/okmahjong",
    registrationLink: "https://oklahomamahjong.com/tournament/",
    description: "ARA-certified annual riichi mahjong tournament by Oklahoma Mahjong. 2025 WRC rules with optional mods. Format: 7-hanchan scramble + top-4 cut final bracket. Sat–Sun, March 14–15, 2026 at Embassy Suites Tulsa. Prizes: custom trophies and plated riichi sticks (1st–4th), medals (5th–8th).",
    howToJoin: "Register via tournament page; pay Ashlee Leak via Venmo @ashlee-leak or PayPal @AshleeFeather.",
    whatToBring: "Point sticks provided; bring yourself",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "40-64",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-15",
    name: "Oklahoma Mahjong – Tulsa Saturday @ Wizards Asylum",
    organizerName: "Zac Leak",
    type: "open_play",
    gameStyle: "riichi",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "Wizards Asylum Comics & Games",
    address: "7165 S Mingo Rd, Tulsa, OK 74133",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "saturday",
      startTime: "13:00",
      endTime: "17:00",
      frequency: "weekly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0.0,
    contactName: "Zac Leak",
    contactEmail: "",
    contactPhone: "",
    website: "https://oklahomamahjong.com",
    instagram: "@ok.mahjong",
    facebookGroup: "https://www.facebook.com/groups/okmahjong",
    registrationLink: "",
    description: "Weekly riichi mahjong open play hosted by Oklahoma Mahjong's Tulsa chapter. Full hanchan (east + south rounds). All skill levels welcome.",
    howToJoin: "Drop in; check OKM Facebook/Discord for updates/cancellations.",
    whatToBring: "Yourself; sets provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "8-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-16",
    name: "Oklahoma Mahjong – Tulsa Sunday @ 2D6 Games",
    organizerName: "Zac Leak",
    type: "open_play",
    gameStyle: "riichi",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "2D6 Games",
    address: "6939 E 71st St, Tulsa, OK 74133",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "sunday",
      startTime: "13:00",
      endTime: "17:00",
      frequency: "weekly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0.0,
    contactName: "Zac Leak",
    contactEmail: "",
    contactPhone: "",
    website: "https://oklahomamahjong.com",
    instagram: "@ok.mahjong",
    facebookGroup: "https://www.facebook.com/groups/okmahjong",
    registrationLink: "",
    description: "Weekly riichi mahjong open play at 2D6 Games, Tulsa host chapter of Oklahoma Mahjong. Full hanchan format.",
    howToJoin: "Drop in; confirm via OKM Facebook/Discord.",
    whatToBring: "Yourself; sets provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "8-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-17",
    name: "Tuesday Tiles – Open Play Mahjong @ The Summit Club",
    organizerName: "",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Downtown Tulsa",
    venueName: "The Summit Club – Overlook Lounge",
    address: "15 W 6th St, 31st Floor, Tulsa, OK 74119",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "tuesday",
      startTime: "17:00",
      endTime: "",
      frequency: "monthly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Members only",
    costAmount: null,
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    website: "https://www.summittulsa.com/events/mahjong",
    instagram: "",
    facebookGroup: "",
    registrationLink: "https://www.summittulsa.com/events/mahjong",
    description: "Monthly American Mahjong open play on the third Tuesday in the Overlook Lounge, 31st floor. For players who already know how to play. 1–2 sets available first-come; members encouraged to bring own tiles. Tables of 4.",
    howToJoin: "Summit Club members only; reserve a table of 4.",
    whatToBring: "Own mahjong tiles and NMJL card recommended",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-18",
    name: "The Mahjong Social Club – Lessons (Tulsa)",
    organizerName: "Courtney Wilson & Heather Duncan",
    type: "lesson",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Tulsa",
    venueName: "Various partner venues",
    address: "Tulsa, OK",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: null,
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Varies",
    costAmount: null,
    contactName: "Courtney Wilson & Heather Duncan",
    contactEmail: "",
    contactPhone: "",
    website: "https://www.mahjsocial.com",
    instagram: "",
    facebookGroup: "",
    registrationLink: "https://www.mahjsocial.com",
    description: "Tulsa's largest American Mahjong community (est. 2023). Beginner 2-hour lessons (4:1 student/teacher ratio), 6-week leagues, open play nights, strategy workshops, Camp Mahj retreats, corporate events, fundraisers. Seven instructors.",
    howToJoin: "Book via mahjsocial.com; private group lessons available.",
    whatToBring: "Nothing; all sets, racks, mats, NMJL cards provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-19",
    name: "The Mahjong Social Club – League Play (Tulsa)",
    organizerName: "Courtney Wilson & Heather Duncan",
    type: "league",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Tulsa",
    venueName: "Various partner venues",
    address: "Tulsa, OK",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: null,
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Varies",
    costAmount: null,
    contactName: "Courtney Wilson & Heather Duncan",
    contactEmail: "",
    contactPhone: "",
    website: "https://www.mahjsocial.com/pages/leagues",
    instagram: "",
    facebookGroup: "",
    registrationLink: "https://www.mahjsocial.com/pages/leagues",
    description: "Six-week American Mahjong league with prizes run by The Mahjong Social Club at partner venues around Tulsa.",
    howToJoin: "Register via TMSC website when current season opens.",
    whatToBring: "NMJL card; sets provided",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "8-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-20",
    name: "OK Let's Mahjong – Tulsa Lessons & Events",
    organizerName: "",
    type: "lesson",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Tulsa",
    venueName: "Mobile / partner venues",
    address: "Tulsa, OK",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: null,
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$80",
    costAmount: 80.0,
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    website: "https://www.okletsmahjong.com/tulsa",
    instagram: "@okletsmahjong",
    facebookGroup: "",
    registrationLink: "https://www.okletsmahjong.com/tulsa",
    description: "Private first-time lessons (2.5 hrs, 4–16 players, $80/pp), follow-up lessons ($60/pp), and social league nights in Tulsa. Instructors come to you.",
    howToJoin: "Book via website; check events page for upcoming social nights.",
    whatToBring: "Nothing; all materials provided",
    skillLevels: ["beginner", "intermediate"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "tul-21",
    name: "Main Street Mahjong – Classes & Monthly Social Play (Broken Arrow)",
    organizerName: "Jalinda H.",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "Broken Arrow / Tulsa Metro",
    venueName: "Various (Broken Arrow area)",
    address: "Broken Arrow, OK 74012",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: null,
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Varies",
    costAmount: null,
    contactName: "Jalinda H.",
    contactEmail: "mainstreetmahjong@gmail.com",
    contactPhone: "",
    website: "https://mainstreetmahjong.com",
    instagram: "",
    facebookGroup: "https://www.facebook.com/groups/1866017190884601",
    registrationLink: "https://mainstreetmahjong.com",
    description: "Broken Arrow American Mahjong community with beginner/intermediate classes, monthly pop-up social play, themed nights, and friendly tournaments. YouTube channel for NMJL card tutorials.",
    howToJoin: "Message via website or Facebook group; check Events page for monthly pop-up dates.",
    whatToBring: "NMJL card; sets typically provided",
    skillLevels: ["beginner", "intermediate"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-22",
    name: "Oklahoma Mahjong – OKC Thursday Riichi @ McNellie's",
    organizerName: "Bill Velten; Terri Suppa-Velten",
    type: "open_play",
    gameStyle: "riichi",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Midtown OKC",
    venueName: "McNellie's Pub OKC",
    address: "1100 Classen Dr, Oklahoma City, OK 73103",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "thursday",
      startTime: "11:00",
      endTime: "",
      frequency: "weekly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0.0,
    contactName: "Bill Velten; Terri Suppa-Velten",
    contactEmail: "",
    contactPhone: "",
    website: "https://oklahomamahjong.com",
    instagram: "@ok.mahjong",
    facebookGroup: "https://www.facebook.com/groups/okmahjong",
    registrationLink: "",
    description: "Weekly riichi mahjong open play at McNellie's Pub, Midtown OKC. Full hanchan format. All skill levels welcome.",
    howToJoin: "Drop in; check OKM Facebook/Discord for updates.",
    whatToBring: "Yourself; sets provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-23",
    name: "Oklahoma Mahjong – OKC Wednesday American (NMJL) @ McNellie's",
    organizerName: "",
    type: "open_play",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Midtown OKC",
    venueName: "McNellie's Pub OKC",
    address: "1100 Classen Dr, Oklahoma City, OK 73103",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "wednesday",
      startTime: "12:00",
      endTime: "",
      frequency: "weekly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0.0,
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    website: "https://oklahomamahjong.com",
    instagram: "@ok.mahjong",
    facebookGroup: "https://www.facebook.com/groups/okmahjong",
    registrationLink: "",
    description: "Free weekly American Mahjong (NMJL) open play at McNellie's Pub, Midtown OKC. Noon start. One of the only regular, free, public American Mahjong sessions in Oklahoma.",
    howToJoin: "Drop in; confirm via OKM Facebook/Discord.",
    whatToBring: "NMJL card; sets available",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-12",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-24",
    name: "Pink Sparrow Mahjong – Pickled Tiles Monday Open Play (Edmond)",
    organizerName: "",
    type: "open_play",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "Pink Sparrow Mahjong",
    address: "124 E 5th St, Suite 250, Edmond, OK 73034",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "monday",
      startTime: "18:30",
      endTime: "21:00",
      frequency: "weekly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$15",
    costAmount: 15.0,
    contactName: "",
    contactEmail: "",
    contactPhone: "405-687-0990",
    website: "https://pinksparrowmahjong.carrd.co",
    instagram: "@pinksparrowmahjong",
    facebookGroup: "",
    registrationLink: "https://calendly.com/pickleproductions4/monday-mahj-pickled-tiles",
    description: "Weekly American Mahjong open play on automatic tables at Pink Sparrow Mahjong's dedicated Edmond studio. Called 'Pickled Tiles Monday Mahj.' OMM-certified instructor.",
    howToJoin: "Sign up via Calendly ($15). Call/text 405-687-0990.",
    whatToBring: "NMJL card; automatic tables provided",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-8",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-25",
    name: "Pink Sparrow Mahjong – Mahjong 101 Class (Edmond)",
    organizerName: "",
    type: "lesson",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "Pink Sparrow Mahjong",
    address: "124 E 5th St, Suite 250, Edmond, OK 73034",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "monday",
      startTime: "18:00",
      endTime: "21:00",
      frequency: "weekly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$60",
    costAmount: 60.0,
    contactName: "",
    contactEmail: "",
    contactPhone: "405-687-0990",
    website: "https://pinksparrowmahjong.carrd.co",
    instagram: "@pinksparrowmahjong",
    facebookGroup: "",
    registrationLink: "https://calendly.com/pickleproductions4/let-s-get-crackin-mahj-101-now-on-monday-s",
    description: "Beginner Mahjong 101 class at Pink Sparrow Mahjong's dedicated studio. OMM-certified instructor. Instruction only — kit/card not included in price.",
    howToJoin: "Register via Calendly. Call/text 405-687-0990.",
    whatToBring: "Nothing; tables and materials provided (kit not included)",
    skillLevels: ["beginner"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-8",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-26",
    name: "Oklahoma Mahjong – Edmond Biweekly @ Edmond Unplugged",
    organizerName: "Jerel Cowan; Joe Schmidt",
    type: "open_play",
    gameStyle: "riichi",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "Edmond Unplugged",
    address: "Edmond, OK (verify exact address via OKM Discord)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "sunday",
      startTime: "13:00",
      endTime: "",
      frequency: "biweekly"
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0.0,
    contactName: "Jerel Cowan; Joe Schmidt",
    contactEmail: "",
    contactPhone: "",
    website: "https://oklahomamahjong.com",
    instagram: "@ok.mahjong",
    facebookGroup: "https://www.facebook.com/groups/okmahjong",
    registrationLink: "",
    description: "Biweekly riichi mahjong at Edmond Unplugged, every other Sunday at 1 PM. Hosted by Oklahoma Mahjong's Edmond chapter.",
    howToJoin: "Drop in; check OKM Facebook/Discord for exact biweekly dates.",
    whatToBring: "Yourself; sets provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-12",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-27",
    name: "OK Let's Mahjong – OKC Lessons & Social Events",
    organizerName: "Sydney Rainey",
    type: "lesson",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "OKC",
    venueName: "Mobile / partner venues",
    address: "Oklahoma City, OK",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: null,
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$80",
    costAmount: 80.0,
    contactName: "Sydney Rainey",
    contactEmail: "",
    contactPhone: "",
    website: "https://www.okletsmahjong.com/oklahoma-city",
    instagram: "@okletsmahjong",
    facebookGroup: "",
    registrationLink: "https://www.okletsmahjong.com/oklahoma-city",
    description: "American Mahjong lessons and social events in OKC. First-time lessons ($80/pp, 2.5 hrs), follow-up strategy lessons ($60/pp), social league nights, 20s Mahj Club. Bradford House and The Green House are regular venues.",
    howToJoin: "Book via website; check events calendar for OKC social nights.",
    whatToBring: "Nothing; all materials provided",
    skillLevels: ["beginner", "intermediate"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-28",
    name: "Edmond Mahj Moms – Lessons & Custom Oklahoma Sets",
    organizerName: "Kelli Miller & Allison Fannon",
    type: "lesson",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / OKC Metro",
    venueName: "Various (mobile, statewide)",
    address: "Edmond, OK",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: null,
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Varies",
    costAmount: null,
    contactName: "Kelli Miller & Allison Fannon",
    contactEmail: "",
    contactPhone: "",
    website: "https://edmondmahjmoms.com",
    instagram: "@edmondmahjmoms",
    facebookGroup: "",
    registrationLink: "https://edmondmahjmoms.com",
    description: "Two Edmond women offering American Mahjong lessons statewide and selling custom Oklahoma-themed tile sets (waving wheat, thunderstorm designs). Teach book clubs, community gatherings, and large groups. Also sell travel-sized NMJL cards.",
    howToJoin: "DM @edmondmahjmoms on Instagram or contact via website.",
    whatToBring: "Nothing; sets provided for lessons",
    skillLevels: ["beginner", "intermediate"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-29",
    name: "Norman Mahjong Club – Classes & Social Play (Norman)",
    organizerName: "Katie, Lauren, Golden & Kendall",
    type: "lesson",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Norman / South OKC Metro",
    venueName: "Various local Norman businesses",
    address: "Norman, OK",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: null,
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$60",
    costAmount: 60.0,
    contactName: "Katie, Lauren, Golden & Kendall",
    contactEmail: "",
    contactPhone: "",
    website: "https://www.normanmahjongclub.com",
    instagram: "@normanmahjongclub",
    facebookGroup: "https://www.facebook.com/p/Norman-Mahjong-Club-61578102298220",
    registrationLink: "https://www.normanmahjongclub.com",
    description: "Norman-based American Mahjong club. Beginner Mahjong 101 classes ($60/pp, 2 hrs, groups of 4 ideal), casual open play, and a social league launching soon. Held at various Norman businesses. Everything provided.",
    howToJoin: "Book via website (Calendly); check Instagram/Facebook for upcoming events.",
    whatToBring: "Nothing; all equipment provided",
    skillLevels: ["beginner", "intermediate"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-12",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-30",
    name: "Oklahoma Mahjong – Equinox In-Person League",
    organizerName: "",
    type: "league",
    gameStyle: "riichi",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "OKC / Statewide",
    venueName: "Various OKM chapter venues",
    address: "Oklahoma, OK",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: true,
    recurringSchedule: null,
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0.0,
    contactName: "",
    contactEmail: "",
    contactPhone: "",
    website: "https://oklahomamahjong.com/equinox-league",
    instagram: "@ok.mahjong",
    facebookGroup: "https://www.facebook.com/groups/okmahjong",
    registrationLink: "https://oklahomamahjong.com/equinox-league",
    description: "Seasonal in-person riichi mahjong league across Oklahoma Mahjong chapter venues. Vernal Equinox (spring) and Autumnal Equinox (fall) seasons. Online Four Seasons League also available year-round.",
    howToJoin: "Check oklahomamahjong.com for current season and registration.",
    whatToBring: "Sets provided at chapter venues",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "8-30",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-31",
    name: "OK Let's Mahjong – Mahjong at Bridging Vines Winery & Brewery (Mar 5)",
    organizerName: "",
    type: "open_play",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Yukon / West OKC",
    venueName: "Bridging Vines Winery & Brewery",
    address: "11216 North Cimarron Road, Yukon, OK 73099",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-05",
    eventStartTime: "18:30",
    eventEndTime: "21:00",
    cost: "$80 lesson / $40 open play",
    costAmount: 40.0,
    contactName: "",
    contactEmail: "hello@okletsmahjong.com",
    contactPhone: "",
    website: "https://www.okletsmahjong.com/events",
    instagram: "@okletsmahjong",
    facebookGroup: "",
    registrationLink: "https://OKLetsMahjong.as.me/?appointmentType=88265649",
    description: "Social mahjong night at Bridging Vines Winery & Brewery in Yukon. First-timers get guided instruction on tiles, the card, rules, and game flow. Open play guests jump right in with instructor support. Come solo or bring friends.",
    howToJoin: "Book via OKLetsMahjong.as.me — first-time lesson ($80) or open play ($40) listed separately.",
    whatToBring: "Nothing; all sets and materials provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-32",
    name: "OK Let's Mahjong – Mahjong at Citizen House (Mar 12)",
    organizerName: "",
    type: "open_play",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "OKC",
    venueName: "Citizen House OKC",
    address: "Oklahoma City, OK (confirm exact address via event page)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-12",
    eventStartTime: "11:30",
    eventEndTime: "14:30",
    cost: "$80 lesson / $40 open play",
    costAmount: 40.0,
    contactName: "",
    contactEmail: "hello@okletsmahjong.com",
    contactPhone: "",
    website: "https://www.okletsmahjong.com/events",
    instagram: "@okletsmahjong",
    facebookGroup: "",
    registrationLink: "https://OKLetsMahjong.as.me/?appointmentType=83616153",
    description: "Mahjong at Citizen House — open to members and non-members. Venue tours + complimentary champagne at 11:30 AM, mahjong at noon. Beginners get step-by-step instruction; experienced players join open play with instructor tips. Food and drinks for purchase. 48-hr cancellation policy.",
    howToJoin: "Book via OKLetsMahjong.as.me — $40 open play or $80 beginner lesson (+$3 booking fee).",
    whatToBring: "Nothing; all provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-33",
    name: "Edmond Mahj Moms – Sunday Funday @ Frenzy Brewing (Mar 8)",
    organizerName: "Kelli Miller & Allison Fannon",
    type: "open_play",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "Frenzy Brewing",
    address: "15 S Broadway, Edmond, OK 73034",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-08",
    eventStartTime: "",
    eventEndTime: "",
    cost: "From $25",
    costAmount: 25.0,
    contactName: "Kelli Miller & Allison Fannon",
    contactEmail: "",
    contactPhone: "405-658-5374",
    website: "https://edmondmahjmoms.com/collections/events-1",
    instagram: "@edmondmahjmoms",
    facebookGroup: "",
    registrationLink: "https://edmondmahjmoms.com/collections/events-1",
    description: "Sunday Funday social American Mahjong at Frenzy Brewing in downtown Edmond. Hosted by Edmond Mahj Moms. Fun, casual play — drinks available at the brewery.",
    howToJoin: "Register via edmondmahjmoms.com/collections/events-1.",
    whatToBring: "NMJL card if you have one; sets provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-34",
    name: "Edmond Mahj Moms – Open Social Play @ Frenzy Brewing (Mar 12)",
    organizerName: "Kelli Miller & Allison Fannon",
    type: "open_play",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "Frenzy Brewing",
    address: "15 S Broadway, Edmond, OK 73034",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-12",
    eventStartTime: "",
    eventEndTime: "",
    cost: "$25",
    costAmount: 25.0,
    contactName: "Kelli Miller & Allison Fannon",
    contactEmail: "",
    contactPhone: "405-658-5374",
    website: "https://edmondmahjmoms.com/collections/events-1",
    instagram: "@edmondmahjmoms",
    facebookGroup: "",
    registrationLink: "https://edmondmahjmoms.com/collections/events-1",
    description: "Open social American Mahjong play at Frenzy Brewing, hosted by Edmond Mahj Moms.",
    howToJoin: "Register via edmondmahjmoms.com/collections/events-1.",
    whatToBring: "NMJL card if you have one; sets provided",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-35",
    name: "Edmond Mahj Moms – Mahj for a Cause: Prairie Vale Elementary (Mar 26)",
    organizerName: "Kelli Miller & Allison Fannon",
    type: "event",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "TBA",
    address: "Edmond, OK (confirm via event page)",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-26",
    eventStartTime: "",
    eventEndTime: "",
    cost: "From $40",
    costAmount: 40.0,
    contactName: "Kelli Miller & Allison Fannon",
    contactEmail: "",
    contactPhone: "405-658-5374",
    website: "https://edmondmahjmoms.com/collections/events-1",
    instagram: "@edmondmahjmoms",
    facebookGroup: "",
    registrationLink: "https://edmondmahjmoms.com/collections/events-1",
    description: "Charity mahjong fundraiser benefiting Prairie Vale Elementary School. Play American Mahjong while supporting a local school. Hosted by Edmond Mahj Moms.",
    howToJoin: "Register via edmondmahjmoms.com/collections/events-1.",
    whatToBring: "NMJL card if you have one; sets provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-24",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-36",
    name: "Edmond Mahj Moms – Sunday Funday @ The Mahj House (Mar 29)",
    organizerName: "Kelli Miller & Allison Fannon",
    type: "open_play",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "The Mahj House",
    address: "14008 Plymouth Crossing, Edmond, OK 73013",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-29",
    eventStartTime: "",
    eventEndTime: "",
    cost: "From $25",
    costAmount: 25.0,
    contactName: "Kelli Miller & Allison Fannon",
    contactEmail: "",
    contactPhone: "405-658-5374",
    website: "https://edmondmahjmoms.com/collections/events-1",
    instagram: "@edmondmahjmoms",
    facebookGroup: "",
    registrationLink: "https://edmondmahjmoms.com/collections/events-1",
    description: "Sunday Funday American Mahjong at The Mahj House — Edmond Mahj Moms' dedicated mahjong venue. Pre-opening soft launch event ahead of the official April 10 Grand Opening.",
    howToJoin: "Register via edmondmahjmoms.com/collections/events-1.",
    whatToBring: "NMJL card if you have one; sets provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-37",
    name: "Edmond Mahj Moms – Daytime Open Social Play @ The Mahj House (Mar 31)",
    organizerName: "Kelli Miller & Allison Fannon",
    type: "open_play",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "The Mahj House",
    address: "14008 Plymouth Crossing, Edmond, OK 73013",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-03-31",
    eventStartTime: "",
    eventEndTime: "",
    cost: "$25",
    costAmount: 25.0,
    contactName: "Kelli Miller & Allison Fannon",
    contactEmail: "",
    contactPhone: "405-658-5374",
    website: "https://edmondmahjmoms.com/collections/events-1",
    instagram: "@edmondmahjmoms",
    facebookGroup: "",
    registrationLink: "https://edmondmahjmoms.com/collections/events-1",
    description: "Daytime open social American Mahjong at The Mahj House. Pre-opening soft launch before the April 10 Grand Opening.",
    howToJoin: "Register via edmondmahjmoms.com/collections/events-1.",
    whatToBring: "NMJL card if you have one; sets provided",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-38",
    name: "Edmond Mahj Moms – Evening Open Social Play @ The Mahj House (Apr 1)",
    organizerName: "Kelli Miller & Allison Fannon",
    type: "open_play",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "The Mahj House",
    address: "14008 Plymouth Crossing, Edmond, OK 73013",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-04-01",
    eventStartTime: "",
    eventEndTime: "",
    cost: "$25",
    costAmount: 25.0,
    contactName: "Kelli Miller & Allison Fannon",
    contactEmail: "",
    contactPhone: "405-658-5374",
    website: "https://edmondmahjmoms.com/collections/events-1",
    instagram: "@edmondmahjmoms",
    facebookGroup: "",
    registrationLink: "https://edmondmahjmoms.com/collections/events-1",
    description: "Evening open social American Mahjong at The Mahj House. Pre-opening soft launch before the April 10 Grand Opening.",
    howToJoin: "Register via edmondmahjmoms.com/collections/events-1.",
    whatToBring: "NMJL card if you have one; sets provided",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-16",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-39",
    name: "Edmond Mahj Moms – The Mahj House Grand Opening (Apr 10)",
    organizerName: "Kelli Miller & Allison Fannon",
    type: "event",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "The Mahj House",
    address: "14008 Plymouth Crossing, Edmond, OK 73013",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: "2026-04-10",
    eventStartTime: "",
    eventEndTime: "",
    cost: "Free",
    costAmount: 0.0,
    contactName: "Kelli Miller & Allison Fannon",
    contactEmail: "",
    contactPhone: "405-658-5374",
    website: "https://edmondmahjmoms.com/collections/events-1",
    instagram: "@edmondmahjmoms",
    facebookGroup: "",
    registrationLink: "https://edmondmahjmoms.com/products/grand-opening-table-booking-april-10th",
    description: "Grand Opening of The Mahj House — Edmond Mahj Moms' dedicated American Mahjong venue in Edmond, OK. Reserve a free table for the celebration. Likely Oklahoma's first dedicated mahjong venue. All are welcome!",
    howToJoin: "Reserve a free table via edmondmahjmoms.com/collections/events-1.",
    whatToBring: "Nothing; all provided",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "4-40",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
  {
    id: "okl-40",
    name: "Edmond Mahj Moms – Spring League @ The Mahj House",
    organizerName: "Kelli Miller & Allison Fannon",
    type: "league",
    gameStyle: "american",
    city: "Oklahoma City",
    state: "OK",
    generalArea: "Edmond / North OKC",
    venueName: "The Mahj House",
    address: "14008 Plymouth Crossing, Edmond, OK 73013",
    geopoint: {
      lat: 0,
      lng: 0
    },
    isRecurring: false,
    recurringSchedule: null,
    eventDate: null,
    eventStartTime: "",
    eventEndTime: "",
    cost: "$175",
    costAmount: 175.0,
    contactName: "Kelli Miller & Allison Fannon",
    contactEmail: "",
    contactPhone: "405-658-5374",
    website: "https://edmondmahjmoms.com/collections/events-1",
    instagram: "@edmondmahjmoms",
    facebookGroup: "",
    registrationLink: "https://edmondmahjmoms.com/products/spring-league-at-the-mahj-house",
    description: "Seasonal American Mahjong league at The Mahj House. Great for solo learners to connect with other players and grow their game. Hosted by Edmond Mahj Moms.",
    howToJoin: "Register via edmondmahjmoms.com/collections/events-1.",
    whatToBring: "NMJL card; sets provided",
    skillLevels: ["beginner", "intermediate"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "8-20",
    imageUrl: "",
    status: "active",
    verified: true,
    claimedBy: null,
    source: "manual",
    promoted: false,
    lastVerified: "2026-03-03",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-03",
  },
];

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "American Mahjong Set with Soft Case",
    category: "sets",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$49.99",
    description: "Complete 166-tile American Mahjong set with racks, pushers, and carrying case. Perfect for beginners.",
    featured: true,
  },
  {
    id: "p2",
    name: "2026 NMJL Card",
    category: "cards",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$15.00",
    description: "Official 2026 National Mah Jongg League card. Required for American Mahjong play.",
    featured: true,
  },
  {
    id: "p3",
    name: "Mahjong for Beginners Book",
    category: "books",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$14.99",
    description: "Learn the fundamentals of Mahjong with clear instructions and color illustrations.",
    featured: true,
  },
  {
    id: "p4",
    name: "Premium Wooden Tile Racks (Set of 4)",
    category: "accessories",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$29.99",
    description: "Handcrafted wooden tile racks. Fits all standard tile sizes.",
    featured: false,
  },
  {
    id: "p5",
    name: "Travel Mahjong Set",
    category: "sets",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$34.99",
    description: "Compact travel set perfect for playing on the go. Fits in carry-on luggage.",
    featured: true,
  },
  {
    id: "p6",
    name: "'I'd Rather Be Playing Mahj' Tote Bag",
    category: "apparel",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$18.99",
    description: "Stylish canvas tote bag perfect for carrying your tiles to game night.",
    featured: false,
  },
];

export function getGamesByCity(city: string): Game[] {
  return mockGames.filter(
    (g) => g.city.toLowerCase() === city.toLowerCase() && g.status === "active"
  );
}

export function getGamesByState(state: string): Game[] {
  return mockGames.filter(
    (g) => g.state.toLowerCase() === state.toLowerCase() && g.status === "active"
  );
}

export function getCitiesWithGames(): { city: string; state: string; count: number }[] {
  const cityMap = new Map<string, { city: string; state: string; count: number }>();
  for (const game of mockGames) {
    if (game.status !== "active") continue;
    const key = `${game.city}-${game.state}`;
    const existing = cityMap.get(key);
    if (existing) {
      existing.count++;
    } else {
      cityMap.set(key, { city: game.city, state: game.state, count: 1 });
    }
  }
  return Array.from(cityMap.values());
}

export function getStatesWithGames(): { state: string; stateName: string; cityCount: number; gameCount: number }[] {
  const stateMap = new Map<string, { cities: Set<string>; gameCount: number }>();
  for (const game of mockGames) {
    if (game.status !== "active") continue;
    const existing = stateMap.get(game.state);
    if (existing) {
      existing.cities.add(game.city);
      existing.gameCount++;
    } else {
      stateMap.set(game.state, { cities: new Set([game.city]), gameCount: 1 });
    }
  }
  const { US_STATES } = require("@/lib/constants");
  return Array.from(stateMap.entries()).map(([state, data]) => ({
    state,
    stateName: US_STATES[state] || state,
    cityCount: data.cities.size,
    gameCount: data.gameCount,
  }));
}
