import { Game, Product } from "@/types";

export const mockGames: Game[] = [
  {
    id: "1",
    name: "Tuesday Night Mahj at McNellie's",
    organizerName: "Mahj918",
    type: "open_play",
    gameStyle: "american",
    city: "Tulsa",
    state: "OK",
    generalArea: "South Tulsa",
    venueName: "McNellie's South City",
    address: "7031 S Zurich Ave, Tulsa, OK 74136",
    geopoint: { lat: 36.0844, lng: -95.9382 },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "tuesday",
      startTime: "18:00",
      endTime: "20:30",
      frequency: "weekly",
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$15",
    costAmount: 15,
    contactName: "Candace",
    contactEmail: "mahj918@yahoo.com",
    contactPhone: "",
    website: "https://linktr.ee/mahj918",
    instagram: "@mahj.918",
    facebookGroup: "",
    registrationLink: "",
    description:
      "Open play for all skill levels. Sets provided. Cash bar and food available. Come enjoy a relaxing evening of American Mahjong!",
    howToJoin: "Just show up! No RSVP needed.",
    whatToBring: "Bring your NMJL card. Sets provided.",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "3-5 tables",
    imageUrl: "",
    status: "active",
    claimedBy: null,
    source: "manual",
    lastVerified: "2026-02-28T00:00:00Z",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-02-28T00:00:00Z",
  },
  {
    id: "2",
    name: "Nashville Mahj Meetup",
    organizerName: "Music City Mahjong",
    type: "open_play",
    gameStyle: "american",
    city: "Nashville",
    state: "TN",
    generalArea: "East Nashville",
    venueName: "East Side Story Coffee",
    address: "1214 Woodland St, Nashville, TN 37206",
    geopoint: { lat: 36.1745, lng: -86.7569 },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "wednesday",
      startTime: "14:00",
      endTime: "17:00",
      frequency: "weekly",
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0,
    contactName: "Sarah",
    contactEmail: "musiccitymahj@gmail.com",
    contactPhone: "615-555-0123",
    website: "",
    instagram: "@musiccitymahj",
    facebookGroup: "https://facebook.com/groups/musiccitymahj",
    registrationLink: "",
    description:
      "Casual weekly mahjong at a great coffee shop. Beginners welcome! We'll teach you if you're new. Great vibes and great lattes.",
    howToJoin: "Just show up or DM us on Instagram!",
    whatToBring: "Nothing needed — sets and cards provided.",
    skillLevels: ["beginner", "intermediate"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: 20,
    typicalGroupSize: "2-4 tables",
    imageUrl: "",
    status: "active",
    claimedBy: null,
    source: "manual",
    lastVerified: "2026-03-01T00:00:00Z",
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Denver Dragon Tiles League",
    organizerName: "Denver Dragon Tiles",
    type: "league",
    gameStyle: "american",
    city: "Denver",
    state: "CO",
    generalArea: "Capitol Hill",
    venueName: "Board Game Republic",
    address: "520 E Colfax Ave, Denver, CO 80203",
    geopoint: { lat: 39.7402, lng: -104.9795 },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "thursday",
      startTime: "19:00",
      endTime: "22:00",
      frequency: "weekly",
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$10",
    costAmount: 10,
    contactName: "Mike",
    contactEmail: "denverdragon@gmail.com",
    contactPhone: "",
    website: "https://denverdragonmahj.com",
    instagram: "@denverdragonmahj",
    facebookGroup: "",
    registrationLink: "https://denverdragonmahj.com/register",
    description:
      "Competitive American Mahjong league. Seasonal standings, prizes for top players. Serious but friendly!",
    howToJoin: "Register on our website before attending.",
    whatToBring: "Bring your NMJL card and your A-game.",
    skillLevels: ["intermediate", "advanced"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: 32,
    typicalGroupSize: "6-8 tables",
    imageUrl: "",
    status: "active",
    claimedBy: null,
    source: "manual",
    lastVerified: "2026-02-25T00:00:00Z",
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-02-25T00:00:00Z",
  },
  {
    id: "4",
    name: "Beginner Mahjong Workshop",
    organizerName: "Birdy Basics Nashville",
    type: "lesson",
    gameStyle: "american",
    city: "Nashville",
    state: "TN",
    generalArea: "The Gulch",
    venueName: "Nashville Public Library - Main",
    address: "615 Church St, Nashville, TN 37219",
    geopoint: { lat: 36.1608, lng: -86.7816 },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "saturday",
      startTime: "10:00",
      endTime: "12:00",
      frequency: "monthly",
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$25",
    costAmount: 25,
    contactName: "Lisa",
    contactEmail: "birdybasics@gmail.com",
    contactPhone: "615-555-0456",
    website: "https://birdybasicsnash.com",
    instagram: "@birdybasicsnash",
    facebookGroup: "",
    registrationLink: "https://birdybasicsnash.com/workshops",
    description:
      "Learn American Mahjong from scratch! Perfect for complete beginners. Includes rules overview, hands-on practice, and your first game.",
    howToJoin: "Register on our website — spots fill up fast!",
    whatToBring: "Just bring yourself! All materials provided.",
    skillLevels: ["beginner"],
    dropInFriendly: false,
    setsProvided: true,
    maxPlayers: 16,
    typicalGroupSize: "3-4 tables",
    imageUrl: "",
    status: "active",
    claimedBy: null,
    source: "manual",
    lastVerified: "2026-02-20T00:00:00Z",
    createdAt: "2026-01-05T00:00:00Z",
    updatedAt: "2026-02-20T00:00:00Z",
  },
  {
    id: "5",
    name: "NYC Chinatown Mahjong Club",
    organizerName: "NY Mahjong Society",
    type: "open_play",
    gameStyle: "chinese",
    city: "New York",
    state: "NY",
    generalArea: "Chinatown",
    venueName: "Golden Dragon Community Center",
    address: "62 Mott St, New York, NY 10013",
    geopoint: { lat: 40.7157, lng: -73.9989 },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "sunday",
      startTime: "13:00",
      endTime: "18:00",
      frequency: "weekly",
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$5",
    costAmount: 5,
    contactName: "Wei",
    contactEmail: "nymahjongsociety@gmail.com",
    contactPhone: "212-555-0789",
    website: "",
    instagram: "",
    facebookGroup: "https://facebook.com/groups/nymahjongsociety",
    registrationLink: "",
    description:
      "Traditional Chinese Mahjong in the heart of Chinatown. All ages and levels welcome. Refreshments provided.",
    howToJoin: "Walk in anytime between 1-5pm!",
    whatToBring: "Nothing needed — sets available on site.",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "5-10 tables",
    imageUrl: "",
    status: "active",
    claimedBy: null,
    source: "manual",
    lastVerified: "2026-03-02T00:00:00Z",
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-03-02T00:00:00Z",
  },
  {
    id: "6",
    name: "Miami Beach Mahj & Mimosas",
    organizerName: "SoFlo Mahj",
    type: "open_play",
    gameStyle: "american",
    city: "Miami",
    state: "FL",
    generalArea: "South Beach",
    venueName: "The Setai Miami Beach",
    address: "2001 Collins Ave, Miami Beach, FL 33139",
    geopoint: { lat: 25.7959, lng: -80.1282 },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "sunday",
      startTime: "11:00",
      endTime: "14:00",
      frequency: "weekly",
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "$20",
    costAmount: 20,
    contactName: "Rachel",
    contactEmail: "soflomahj@gmail.com",
    contactPhone: "",
    website: "https://soflomahj.com",
    instagram: "@soflomahj",
    facebookGroup: "",
    registrationLink: "",
    description:
      "Mahjong with a tropical twist! Enjoy American Mahj with mimosas on the patio. All levels welcome, great for tourists and snowbirds.",
    howToJoin: "RSVP via Instagram DM or just show up!",
    whatToBring: "Bring your NMJL card. We have sets.",
    skillLevels: ["beginner", "intermediate"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: 24,
    typicalGroupSize: "4-6 tables",
    imageUrl: "",
    status: "active",
    claimedBy: null,
    source: "manual",
    lastVerified: "2026-02-27T00:00:00Z",
    createdAt: "2026-01-12T00:00:00Z",
    updatedAt: "2026-02-27T00:00:00Z",
  },
  {
    id: "7",
    name: "Chicago Riichi Mahjong Club",
    organizerName: "Windy City Riichi",
    type: "open_play",
    gameStyle: "riichi",
    city: "Chicago",
    state: "IL",
    generalArea: "Wicker Park",
    venueName: "Dice Dojo Gaming Lounge",
    address: "1474 N Milwaukee Ave, Chicago, IL 60622",
    geopoint: { lat: 41.9082, lng: -87.6743 },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "friday",
      startTime: "18:30",
      endTime: "23:00",
      frequency: "weekly",
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0,
    contactName: "Ken",
    contactEmail: "windycityriichi@gmail.com",
    contactPhone: "",
    website: "https://windycityriichi.org",
    instagram: "@windycityriichi",
    facebookGroup: "",
    registrationLink: "",
    description:
      "Japanese Riichi Mahjong club. We play on automatic tables! Newcomers to Riichi welcome — we do a tutorial the first Friday of each month.",
    howToJoin: "Join our Discord for table counts, or just show up.",
    whatToBring: "Nothing — automatic tables and tiles provided.",
    skillLevels: ["beginner", "intermediate", "advanced"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: null,
    typicalGroupSize: "3-6 tables",
    imageUrl: "",
    status: "active",
    claimedBy: null,
    source: "manual",
    lastVerified: "2026-03-01T00:00:00Z",
    createdAt: "2026-01-08T00:00:00Z",
    updatedAt: "2026-03-01T00:00:00Z",
  },
  {
    id: "8",
    name: "Dallas Mahjong Social",
    organizerName: "DFW Mahj Group",
    type: "open_play",
    gameStyle: "american",
    city: "Dallas",
    state: "TX",
    generalArea: "Uptown Dallas",
    venueName: "The Loft at Uptown",
    address: "3230 McKinney Ave, Dallas, TX 75204",
    geopoint: { lat: 32.8068, lng: -96.7984 },
    isRecurring: true,
    recurringSchedule: {
      dayOfWeek: "monday",
      startTime: "13:00",
      endTime: "16:00",
      frequency: "weekly",
    },
    eventDate: null,
    eventStartTime: null,
    eventEndTime: null,
    cost: "Free",
    costAmount: 0,
    contactName: "Patricia",
    contactEmail: "dfwmahj@gmail.com",
    contactPhone: "214-555-0234",
    website: "",
    instagram: "@dfwmahj",
    facebookGroup: "https://facebook.com/groups/dfwmahj",
    registrationLink: "",
    description:
      "Friendly Monday afternoon American Mahjong. Coffee and snacks provided. Great group of regulars who love welcoming new players.",
    howToJoin: "Text Patricia or just show up!",
    whatToBring: "NMJL card required. Sets provided.",
    skillLevels: ["beginner", "intermediate"],
    dropInFriendly: true,
    setsProvided: true,
    maxPlayers: 20,
    typicalGroupSize: "3-5 tables",
    imageUrl: "",
    status: "active",
    claimedBy: null,
    source: "manual",
    lastVerified: "2026-02-26T00:00:00Z",
    createdAt: "2026-01-18T00:00:00Z",
    updatedAt: "2026-02-26T00:00:00Z",
  },
];

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "American Mahjong Set with Soft Case",
    category: "sets",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$49.99",
    description: "Complete 166-tile American Mahjong set with racks, pushers, and carrying case. Perfect for beginners.",
    featured: true,
  },
  {
    id: "p2",
    name: "2026 NMJL Card",
    category: "cards",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$15.00",
    description: "Official 2026 National Mah Jongg League card. Required for American Mahjong play.",
    featured: true,
  },
  {
    id: "p3",
    name: "Mahjong for Beginners Book",
    category: "books",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$14.99",
    description: "Learn the fundamentals of Mahjong with clear instructions and color illustrations.",
    featured: true,
  },
  {
    id: "p4",
    name: "Premium Wooden Tile Racks (Set of 4)",
    category: "accessories",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$29.99",
    description: "Handcrafted wooden tile racks. Fits all standard tile sizes.",
    featured: false,
  },
  {
    id: "p5",
    name: "Travel Mahjong Set",
    category: "sets",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$34.99",
    description: "Compact travel set perfect for playing on the go. Fits in carry-on luggage.",
    featured: true,
  },
  {
    id: "p6",
    name: "'I'd Rather Be Playing Mahj' Tote Bag",
    category: "apparel",
    imageUrl: "/images/placeholder-product.png",
    affiliateLink: "#",
    price: "$18.99",
    description: "Stylish canvas tote bag perfect for carrying your tiles to game night.",
    featured: false,
  },
];

export function getGamesByCity(city: string): Game[] {
  return mockGames.filter(
    (g) => g.city.toLowerCase() === city.toLowerCase() && g.status === "active"
  );
}

export function getGamesByState(state: string): Game[] {
  return mockGames.filter(
    (g) => g.state.toLowerCase() === state.toLowerCase() && g.status === "active"
  );
}

export function getCitiesWithGames(): { city: string; state: string; count: number }[] {
  const cityMap = new Map<string, { city: string; state: string; count: number }>();
  for (const game of mockGames) {
    if (game.status !== "active") continue;
    const key = `${game.city}-${game.state}`;
    const existing = cityMap.get(key);
    if (existing) {
      existing.count++;
    } else {
      cityMap.set(key, { city: game.city, state: game.state, count: 1 });
    }
  }
  return Array.from(cityMap.values());
}

export function getStatesWithGames(): { state: string; stateName: string; cityCount: number; gameCount: number }[] {
  const stateMap = new Map<string, { cities: Set<string>; gameCount: number }>();
  for (const game of mockGames) {
    if (game.status !== "active") continue;
    const existing = stateMap.get(game.state);
    if (existing) {
      existing.cities.add(game.city);
      existing.gameCount++;
    } else {
      stateMap.set(game.state, { cities: new Set([game.city]), gameCount: 1 });
    }
  }
  const { US_STATES } = require("@/lib/constants");
  return Array.from(stateMap.entries()).map(([state, data]) => ({
    state,
    stateName: US_STATES[state] || state,
    cityCount: data.cities.size,
    gameCount: data.gameCount,
  }));
}
